# Generated by Django 5.2.4 on 2025-08-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_participant_events_event_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='events',
            field=models.ManyToManyField(related_name='participants', to='tasks.event'),
        ),
    ]
